export const MOCK_USERS = [
  {
    id: "usr_001",
    displayName: "Admin User",
    role: "Administrator",
    branch: "Main Campus",
    email: "admin@hospital.com",
    password: "admin@123",
  },
  {
    id: "usr_002",
    displayName: "Dr. Smith",
    role: "Doctor",
    branch: "North Branch",
    email: "doctor@hospital.com",
    password: "doctor@123",
  },
  {
    id: "usr_003",
    displayName: "Dr. Surgeon",
    role: "Surgeon",
    branch: "Main Campus",
    email: "surgeon@hospital.com",
    password: "surgeon@123",
  },
  {
    id: "usr_004",
    displayName: "Nurse Joy",
    role: "Nurse",
    branch: "South Branch",
    email: "nurse@hospital.com",
    password: "nurse@123",
  },
  {
    id: "usr_005",
    displayName: "Receptionist Alice",
    role: "Receptionist",
    branch: "East Wing",
    email: "reception@hospital.com",
    password: "reception@123",
  },
  {
    id: "usr_006",
    displayName: "Pharmacist Bob",
    role: "Pharmacist",
    branch: "West Medical Center",
    email: "pharmacy@hospital.com",
    password: "pharmacy@123",
  },
  {
    id: "usr_007",
    displayName: "Tech Charlie",
    role: "Lab Technician",
    branch: "Main Campus",
    email: "lab@hospital.com",
    password: "lab@123",
  },
  {
    id: "usr_008",
    displayName: "Patient John",
    role: "Patient",
    branch: "Main Campus",
    email: "patient@hospital.com",
    password: "patient@123",
  },
  {
    id: "usr_009",
    displayName: "Accountant Eve",
    role: "Accountant",
    branch: "Main Campus",
    email: "accountant@hospital.com",
    password: "accountant@123",
  },
  {
    id: "usr_010",
    displayName: "Manager Dave",
    role: "Inventory Manager",
    branch: "Main Campus",
    email: "inventory@hospital.com",
    password: "inventory@123",
  },
];
